KatVR landing
mate-academy/layout_KateVR pull request #69
Opened 2023-03-14 10:45 UTC by Vo7kov

https://vo7kov.github.io/layout_KateVR/

2023-03-14 12:10 UTC, Vo7kov commented
https://vo7kov.github.io/layout_KateVR/

2023-03-14 12:31 UTC, VitaliyBondarenko1982 requested changes
good start.
waiting other sections

2023-03-15 10:14 UTC, Vo7kov commented
https://vo7kov.github.io/layout_KateVR/

2023-03-15 12:06 UTC, IvanFesenko requested changes
Where is first section?
Keep going

2023-03-15 21:54 UTC, Vo7kov commented
https://vo7kov.github.io/layout_KateVR/ - sorry for my js code. I haven't learn it yet, so I just watch tutors in yt and turn on my brain)

2023-03-15 22:00 UTC, Vo7kov commented
https://vo7kov.github.io/layout_KateVR/ - sorry for my js code. I haven't learn it yet, so I just watch tutors in yt and turn on my brain)

2023-03-16 08:40 UTC, OlEzhA0 requested changes
gj! Waiting for next sections

2023-03-20 11:36 UTC, Vo7kov commented
https://vo7kov.github.io/layout_KateVR/ - sorry for my js

2023-03-22 08:18 UTC, etojeDenys requested changes
looks good, keep going!

2023-03-23 08:22 UTC, Vo7kov commented
https://vo7kov.github.io/layout_KateVR/ - in this sections I decided to use some interesting thing for video. Its not default iframe, its picture with button. And when user clicks - it transform to iframe and video is starting playing. I've made this for optimization. And honestly, I find this guy on yt and use his scripts https://www.youtube.com/watch?v=4JS70KB9GS0

2023-03-23 08:51 UTC, OleziO requested changes
Fix this button logic
![image](https://user-images.githubusercontent.com/56752562/227149866-69d8f59e-3718-4037-b6f6-46a714f202b2.png)

Clear form after submission. Prevent page redirecting.

Not released: 
![image](https://user-images.githubusercontent.com/56752562/227150551-4df65e6d-a903-4ad5-8f18-0527d5ed76aa.png)
![image](https://user-images.githubusercontent.com/56752562/227150926-015779ac-8f14-422e-b8cf-c0a8a7c06765.png)

2023-03-28 22:06 UTC, Vo7kov commented
I've added only header without any popups. I wait for header review, and then I'll go to make all popups

2023-03-29 07:19 UTC, etojeDenys requested changes
good job

2023-03-30 17:47 UTC, Vo7kov commented
https://vo7kov.github.io/layout_KateVR/ - I've realized menu, but all I need to add is

- Modal windows in header
- Buy page
- Sticky button (I'll ask at q&a how to add it)

I wait for review and then I'm going to make it

2023-03-31 07:27 UTC, OlEzhA0 requested changes
you missed this detail in header
<img width="50" alt="Screenshot 2023-03-31 at 10 19 22 AM" src="https://user-images.githubusercontent.com/60295799/229051005-abed5a4c-a5d5-4062-92e8-a370c14d157b.png">

2. in section `ABOUT PRODUCT` (video slider) I can start 1 video, then click on `Next` and start 2 video, and I can start all 5 videos at same time, and it's not stop when I change slide

3. would be better to add scroll behaviour smooth
4. I can't send your form, because I don't know which phone format should be. (I tried 5 different formats). Please show some placeholder with right format examples
<img width="638" alt="Screenshot 2023-03-31 at 10 25 14 AM" src="https://user-images.githubusercontent.com/60295799/229052364-6910a59f-be80-4919-a769-3ebb6cb9456c.png">

2023-03-31 08:52 UTC, Vo7kov commented
I fixed the next bugs

- Form placeholder

About the multilang element in header. Mentor said me, that I dont need to do it, because its not working. On this page there are some custom svg text, for example `ABOUT US` in about us section. Its svg text, not markup, so I cant translate it. About videos I'll ask it at q&a. But I already added scroll-behavior

2023-03-31 09:10 UTC, loralevitska requested changes
You did an amazing job! Looks good! Let's do some improvements (check comments)
- add cursor pointer to clickable elements not only hover effect
- video is playing by click on any block on page. fix it
- fix autocomplete background 
![image](https://user-images.githubusercontent.com/70009205/229077506-b17673ed-34ea-4b0e-9c52-db9905ff7439.png)

2023-04-02 14:59 UTC, VitaliyBondarenko1982 requested changes
good job!
please fix autocomplete styles

2023-04-02 16:49 UTC, Vo7kov commented
https://vo7kov.github.io/layout_KateVR/ - I dont know, if its ok, I've disabled autocomplete for inputs

2023-04-03 06:58 UTC, etojeDenys requested changes
looks great, keep going

2023-04-03 12:55 UTC, Vo7kov commented
I've added sticky button, but set position absolute, because in design there is no place for button in footer

2023-04-03 14:41 UTC, mykhalenych requested changes
1.  fix inputs with autocomplete
<img width="774" alt="Screenshot 2023-04-03 at 17 36 05" src="https://user-images.githubusercontent.com/53228259/229542128-85ab2c73-0795-4898-b354-195595b2c4b8.png">
2. buy button looks strange
<img width="1288" alt="Screenshot 2023-04-03 at 17 36 49" src="https://user-images.githubusercontent.com/53228259/229542348-322c66b0-0396-4601-a47f-4fcd92cf0f52.png">
3. button content must be on center
<img width="334" alt="Screenshot 2023-04-03 at 17 38 36" src="https://user-images.githubusercontent.com/53228259/229542877-259189fe-a369-42f5-9ab7-c7a4c98b2537.png">
4. missed many sections
<img width="306" alt="Screenshot 2023-04-03 at 17 40 15" src="https://user-images.githubusercontent.com/53228259/229543362-83a0c5a4-3714-4222-891d-9d05fa8774f8.png">
5. after click on buy must be modal

2023-04-10 17:57 UTC, Vo7kov commented
I've added some simple validation according yt tutorials, because I haven't learn js yet

2023-04-10 18:57 UTC, VitaliyBondarenko1982 requested changes
- autocomplete styles still not fixed. take a look link how to fix
  https://css-tricks.com/snippets/css/change-autocomplete-styles-webkit-browsers/
- position of `buy now` button on tablet and mobile view mismatch with design
  
  design mobile:
![Screenshot from 2023-04-10 21-54-13](https://user-images.githubusercontent.com/33029864/230973386-41643553-93a6-46f1-bb7c-deff39acd46e.png)
 
demo link:
![Screenshot from 2023-04-10 21-55-21](https://user-images.githubusercontent.com/33029864/230973474-8f7bc414-2f8f-4b61-9166-3c55f6307113.png)

2023-04-11 13:51 UTC, mykhalenych requested changes
design:
<img width="198" alt="Screenshot 2023-04-11 at 16 49 03" src="https://user-images.githubusercontent.com/53228259/231183870-31253236-52e1-49e4-8e11-009e1b37b095.png">
deploy:
<img width="189" alt="Screenshot 2023-04-11 at 16 49 14" src="https://user-images.githubusercontent.com/53228259/231183925-7b9686a4-b597-4108-ac5c-192ad1c715be.png">
on tablet button looks different between design
<img width="571" alt="Screenshot 2023-04-11 at 16 51 08" src="https://user-images.githubusercontent.com/53228259/231184474-c5e8f873-8e56-475b-92e6-090239bd928f.png">
also fix autocomplete styles in inputs

2023-04-11 14:27 UTC, Vo7kov commented
https://vo7kov.github.io/layout_KateVR/ - if Maksym means, that I forgot to set `autocomplete: off` for all inputs - I fixed it. If smth else - idk what to do

2023-04-11 14:33 UTC, mykhalenych requested changes
<img width="710" alt="Screenshot 2023-04-11 at 17 33 09" src="https://user-images.githubusercontent.com/53228259/231196414-a205dace-e214-4321-a290-e32c13f13c40.png">

I don't see any changes, autocomplete styles still present

2023-04-12 07:04 UTC, etojeDenys requested changes
keep going

2023-04-12 10:46 UTC, Vo7kov commented
https://vo7kov.github.io/layout_KateVR/

2023-04-12 11:38 UTC, anstsot requested changes
Good job, but there are few fixes to improve your code.
1. some of the fields are not placed in one line
![image](https://user-images.githubusercontent.com/22824431/231444886-ebf2d7f2-9cb7-44db-96d2-a8a3e5d5a2d7.png)

2. faq block is broken on mobile
![image](https://user-images.githubusercontent.com/22824431/231445352-752c73bb-bed5-4dd8-a712-85d11c57a4ed.png)

3. add missing links in menu on mobile
![image](https://user-images.githubusercontent.com/22824431/231445452-cd076516-ca2c-4e08-a0e3-2253478e2bbf.png)

4. fix scrolling in modals (faq and help modals) and please fix help modal as per design
![image](https://user-images.githubusercontent.com/22824431/231445723-418e42d1-b92a-479c-8ca0-7871b7c3fb61.png)

2023-04-12 12:46 UTC, IvanFesenko requested changes
Left comments in fe_chat

2023-04-12 14:33 UTC, Vo7kov commented
https://vo7kov.github.io/layout_KateVR/

2023-04-12 15:12 UTC, mykhalenych approved these changes

2025-07-07 14:20 UTC, closed without merging